### ISSUE TITLE
Possible release ?

### ISSUE THREAD

**Issue by CarlosHdez** [Lepozepo/s3-uploader#1]
Hi, I was just wondering if there a release date?
I really like this library but I'm moving away from meteor and I still need be able to upload files to my S3 bucket.

Thanks.

**Comment by Lepozepo** [comment]
Hey @CarlosHdez ! You should be able to upload with this package already, the feature that's pending right now is delete which isn't too bad. Hope to have that over the weekend ^_^

**Comment by CarlosHdez** [comment]
Great! Thanks for the quick response, and another question, docs for this are the same as the Meteor version ?

**Comment by Lepozepo** [comment]
Nope, they're going to be considerably different, have a look at the example ^_^

**Comment by Lepozepo** [comment]
At some point I'll build a bridge for Meteor and another for React for sure though but I can't guarantee anything on those

**Comment by Lepozepo** [comment]
@CarlosHdez the delete functions work now and properly send errors ^_^. Docs are the next step now :D
