### ISSUE TITLE
Assign path within bucket?

### ISSUE THREAD

**Issue by allenfuller** [Lepozepo/s3-uploader#15]
Thanks so much for creating this great, updated package! I'm migrating from the older Atmosphere package and unsure how to specify the path an upload should go to within a bucket here.

In the Atmosphere package, we could specify the path like so:
```
S3.upload(
      {
        file: thisFile,
        path: pathFolderVariable + '/imports'
      },
      ( error, response ) => {
        ... handle response
      }
    );
```

Is there a similar option in this package?

Thanks!

**Comment by allenfuller** [comment]
Disregard, figured it out! The path can be assigned as part of the key, per [the example](https://github.com/Lepozepo/s3-uploader/blob/master/examples/meteor/server/config.js) in this package.

For others who might have the same question, here's how I was able to set the specific path for files within my S3 bucket:
```
import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { S3Up } from 's3up-server';

const s3up = new S3Up({
  accessKeyId: Meteor.settings.accessKeyId,
  secretAccessKey: Meteor.settings.secretAccessKey,
  bucket: 's3upmeteor',
});

Meteor.methods({
  signUpload() {
    this.unblock();

    const filePath = `${pathFolderVariable}/imports/${Random.id()}`;
    return s3up.signUpload({
      key: filePath,
    });
  },
});
```

**Comment by Lepozepo** [comment]
Yep! Glad you were able to figure it out @allenfuller ^_^ I'll consider adding a `path` alias though, might make adoption easier.
