### ISSUE TITLE
Download required Bucket

### ISSUE THREAD

**Issue by allenfuller** [Lepozepo/s3-uploader#56]
Have just updated the package to 2.0.0 and am wondering if I did something wrong along the way, because now it requires `Bucket` (capitalized -- found that out the hard way) as a parameter when using s3Up.download.

Otherwise, it throughs an error in `@smithy/smithy-client`
```
Error: No value provided for input HTTP label: Bucket.
```
Hope this helps someone! If I have a moment, I will submit a PR for docs update. But... is anyone else running into issues? I had the hardest time getting my state.key.url to not return two forward slashes between the AWS URL and the key.

**Comment by Lepozepo** [comment]
@allenfuller thanks for making note of that, I'll have a look at adding back the alias for sure

**Comment by Lepozepo** [comment]
https://github.com/Lepozepo/s3-uploader/commit/a2f785067ed0c43afca14e7bc365b57733866ade this should do it
