### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by paulincai** [Lepozepo/s3-uploader#6]
Hi @Lepozepo,

how do you suggest we pass metadata details for files? My present interest is for Cache_Control and Expires which are indeed necessary for Cloudfront/ S3 caching.

I am having a modified version of your npm but I am not sure I want to upload it as ... another package. Do you have any plans for this or I should rather go ahead and do my own thing?

The changes I did are in the upload_file.js, authorize.js and the upload method. I initialize a variable with the metadata details and pass it to the method as well as to the uploader. If no metadata is provided, the files upload with Cache_Control = no-cache and Expires = '0' (expired).

Looking forward to hearing from you,
Paul

**Comment by Lepozepo** [comment]
Hey @paulincai I should definitely open up support for it. I'm open to PRs if you want to fork and get it working on your end :D (I don't have any active projects using my package at the moment so that's why it's a bit stale)

**Comment by Lepozepo** [comment]
@paulincai this should now be possible with the latest versions of this project ^_^. The `S3Up.signUpload` function will now accept `bucket`, `expires`, `conditions`, and `fields`.

**Comment by Lepozepo** [comment]
(you'll need to use the new packages though `s3up-client` and `s3up-server`
