### ISSUE TITLE
Update npm to latest version?

### ISSUE THREAD

**Issue by jasongrishkoff** [Lepozepo/s3-uploader#9]
Currently trying to replace Meteor Slingshot with this -- so far working well!  I tried running this using the latest npm version, but ran into the bucket issue that was fixed in #8 so I manually overrode it.  Does the npm package need to be updated to reflect the latest changes?

**Comment by Lepozepo** [comment]
@jasongrishkoff thank you for the PR, now that the package is using aws-sdk's internal methods this should never be a problem again ^_^. Look out for the new version of this package, I've split it into 2 `s3up-client` and `s3up-server` both with considerable patches all around, the client can now take tons of files and the server portion should be much cleaner. More to come!
